<a href="https://colab.research.google.com/github/aws3ma/machine-learning/blob/main/Sc1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings

In [22]:
warnings.filterwarnings('ignore')

In [2]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


In [3]:
ml_folder='/content/drive/MyDrive/ML/'

preprocessing data is require for every project

In [47]:
ds=pd.read_csv(ml_folder+'Data.csv')
ds

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [7]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [8]:
ds.shape

(10, 4)

In [10]:
ds.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

[:,:-1] pour selectionner les 3 premier colonnes

In [48]:
x=ds.iloc[:,:-1]
x

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

[:,-1] pour selectionner la dernier colonne ou feature

In [14]:
y=ds.iloc[:,-1]
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

supprimer les NaN
on ajoute int parce que age est un entier

In [49]:
x['Age']=x['Age'].fillna(int(x['Age'].mean()))
x

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain  38.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [50]:
x['Salary']=x['Salary'].fillna(x['Salary'].mean())
x

Country   Age        Salary
0   France  44.0  72000.000000
1    Spain  27.0  48000.000000
2  Germany  30.0  54000.000000
3    Spain  38.0  61000.000000
4  Germany  40.0  63777.777778
5   France  35.0  58000.000000
6    Spain  38.0  52000.000000
7   France  48.0  79000.000000
8  Germany  50.0  83000.000000
9   France  37.0  67000.000000

convert string to number in features

In [33]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [51]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

In [52]:
x1 = np.array(ct.fit_transform(x))
x1 = x1[:,1:]
x1

array([[0.00000000e+00, 0.00000000e+00, 4.40000000e+01, 7.20000000e+04],
       [0.00000000e+00, 1.00000000e+00, 2.70000000e+01, 4.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 3.00000000e+01, 5.40000000e+04],
       [0.00000000e+00, 1.00000000e+00, 3.80000000e+01, 6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 4.00000000e+01, 6.37777778e+04],
       [0.00000000e+00, 0.00000000e+00, 3.50000000e+01, 5.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 3.80000000e+01, 5.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 4.80000000e+01, 7.90000000e+04],
       [1.00000000e+00, 0.00000000e+00, 5.00000000e+01, 8.30000000e+04],
       [0.00000000e+00, 0.00000000e+00, 3.70000000e+01, 6.70000000e+04]])

In [56]:
x2 = pd.get_dummies(x,drop_first=True)
x2

Age        Salary  Country_Germany  Country_Spain
0  44.0  72000.000000                0              0
1  27.0  48000.000000                0              1
2  30.0  54000.000000                1              0
3  38.0  61000.000000                0              1
4  40.0  63777.777778                1              0
5  35.0  58000.000000                0              0
6  38.0  52000.000000                0              1
7  48.0  79000.000000                0              0
8  50.0  83000.000000                1              0
9  37.0  67000.000000                0              0

y always use labelencoder

In [57]:
from sklearn.preprocessing import LabelEncoder

In [59]:
le = LabelEncoder()
y= le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

split data into 80% train and 20% test

In [60]:
from sklearn.model_selection import train_test_split

In [105]:
# x = np.array(x2)
# y = np.array(y)
x_train, x_test, y_train, y_test=train_test_split(x2,y,random_state=0,train_size=0.8,test_size=0.2)

In [106]:
x_train

Age        Salary  Country_Germany  Country_Spain
4  40.0  63777.777778                1              0
9  37.0  67000.000000                0              0
1  27.0  48000.000000                0              1
6  38.0  52000.000000                0              1
7  48.0  79000.000000                0              0
3  38.0  61000.000000                0              1
0  44.0  72000.000000                0              0
5  35.0  58000.000000                0              0

In [107]:
x_test

Age   Salary  Country_Germany  Country_Spain
2  30.0  54000.0                1              0
8  50.0  83000.0                1              0

In [108]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [109]:
y_test

array([0, 0])

standardization aprés split toujours 

In [110]:
from sklearn.preprocessing import StandardScaler

In [117]:
ss = StandardScaler()
ss.fit(x_train)
x_train1= ss.transform(x_train)
x_train1


array([[ 0.27978024,  0.12381479,  2.64575131, -0.77459667],
       [-0.23673712,  0.46175632, -0.37796447, -0.77459667],
       [-1.95846165, -1.53093341, -0.37796447,  1.29099445],
       [-0.06456467, -1.11141978, -0.37796447,  1.29099445],
       [ 1.65715986,  1.7202972 , -0.37796447, -0.77459667],
       [-0.06456467, -0.16751412, -0.37796447,  1.29099445],
       [ 0.96847005,  0.98614835, -0.37796447, -0.77459667],
       [-0.58108203, -0.48214934, -0.37796447, -0.77459667]])

In [118]:
x_test1= ss.transform(x_test)
x_test1

array([[-1.44194429, -0.90166297,  2.64575131, -0.77459667],
       [ 2.00150476,  2.13981082,  2.64575131, -0.77459667]])